#!/usr/bin/env python

import mailer
import argparse
import sys

def getopts(args=None):
    p = argparse.ArgumentParser()
    p.add_argument('-f', '--From', required=True)
    p.add_argument('-t', '--To', nargs='+')
    p.add_argument('-s', '--Subject', required=True)
    p.add_argument('-A', '--attach', nargs='*')

    return p.parse_args(args)


def main(opts):
    opts.attach = opts.attach or list()

    msg         = mailer.Message()
    msg.To      = opts.To
    msg.From    = opts.From
    msg.Subject = opts.Subject
    msg.Html    = sys.stdin.read()

    map(msg.attach, opts.attach)

    sender = mailer.Mailer()
    sender.send(msg)


if __name__ == '__main__':
    main(getopts())
